---
Name: recurringevents
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - internetrix/silverstripe-recurringevents:css/recurringevents-cms.css
Internetrix\Events\Admin\EventsAdmin:
  extensions:
    - Internetrix\RecurringEvents\Extensions\RecurringEventsModelAdminExtension
Internetrix\Events\Admin\ArchivedEventsAdmin:
  extensions:
    - Internetrix\RecurringEvents\Extensions\RecurringEventsModelAdminExtension
Internetrix\Events\Pages\CalendarEvent:
  extensions:
    - Internetrix\RecurringEvents\Extensions\RecurringEventsExtension
Internetrix\Events\Pages\EventsPage:
  extensions:
    - Internetrix\RecurringEvents\Extensions\RecurringEventsPageExtension
