---
Name: recurringevents
---
LeftAndMain:
  extra_requirements_css:
    - 'recurringevents/css/field-extras.css'
EventsAdmin:
  extensions:
    - 'RecurringEventsModelAdminExtension'
ArchivedEventsAdmin:
  extensions:
    - 'RecurringEventsModelAdminExtension'
GridFieldDetailForm_ItemRequest:
  extensions:
    - GridFieldRecurringEventsItemRequest
CalendarEvent:
  extensions:
    - 'RecurringEventsExtension'